### ISSUE TITLE
cannot drag window

### ISSUE THREAD

**Issue by iosefa** [dotloom/dat-desktop#8]
electron app window cannot be moved around the screen.

**Comment by iosefa** [comment]
This was addressed in https://github.com/dat-land/dat-desktop/pull/536
 However, the error seems to persist.

**Comment by martinheidegger** [comment]
Can you elaborate?

**Comment by iosefa** [comment]
With developer console either on or off, the window is not draggable. Adding the `is-draggable` css class to the html body tag in index.html seemed allows for the entire window to become draggable (see https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#draggable-region), however this is not ideal

**Comment by iosefa** [comment]
I'm looking into this now :-)
